name: fakeshop-cicd
on:
  push:
    branches: ["main"]
  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
      - run: echo "Docker build"
      - run: echo "Enviar para Docker Hub"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
      - run: echo "Configurar kubeconfig"
      - run: echo "Apply"
